default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: nashthedev
  password:
  host: localhost


development:
  <<: *default
  database: pixshare_development

test:
  <<: *default
  database: pixshare_test

production:
  <<: *default
  database: pixshare_production
  username: pixshare
  password: <%= ENV['PIXSHARE_DATABASE_PASSWORD'] %>
